source 'http://gemcutter.org'

gem 'sinatra'
gem 'thin'
gem 'mongo_mapper'
gem 'haml'
gem 'sass'
gem 'loofah'

# gem 'rspec'
# gem 'rack-test'
# gem 'guard'
# gem 'guard-rspec'
# gem 'libnotify'
# gem 'database_cleaner'